### ISSUE TITLE
Texturas faltantes en el RMF de la versión de 1.6

### ISSUE THREAD

**Issue by WorstAquaPlayer** [rolivencia/de_dust2_largo#2]
**En el RMF de la versión de 1.6 faltan estas texturas que parecen no estar presentes en ninguna otra parte:**
CARTEL1
CARTEL2

![jack_G1Jn3NzLJ5](https://user-images.githubusercontent.com/25833407/107857324-9bf32c00-6e0c-11eb-89a0-8bb91dfd4fb5.png)

**Comment by rolivencia** [comment]
Aparentemente las texturas que faltan son las del cartel de Gametracker.com. Supongo que tal vez lo removieron en alguna versión del CS 1.6. 

Si mi conjetura es correcta, no recuerdo si es que el BSP compilado tiene esas texturas agregadas a manera de bundle a la hora de hacer la compilación. Me late un poco que sí, dado que pude correr el mapa en el CS 1.6 actualizado y no me pasó de no ver la textura ingame.

Supongo que podríamos descompilarlo y agregar un .wad ad-hoc para resolver el issue. Decime tu opinión cuando puedas.

**Comment by WorstAquaPlayer** [comment]
Creo que las texturas no están incluidas en ningún BSP, me he fijado en el BSP de este repositorio y en el juego se ve así:
![20210213153435_1](https://user-images.githubusercontent.com/25833407/107858434-d364d700-6e12-11eb-994e-7c1d17ff5911.jpg)

Luego, me baje el BSP de maps.cs-bg.info y 17buddies.rocks, ocurre lo mismo, se ve así:
![20210213153505_1](https://user-images.githubusercontent.com/25833407/107858390-afa19100-6e12-11eb-8122-17863fd9a5b0.jpg)


Utilizando una tool para ver las texturas empacadas en el BSP mismo, se ve que solo hay 2 texturas empacadas en el mapa:
![Half-LifeBSPTextureTools_QTHOskWBWj](https://user-images.githubusercontent.com/25833407/107858549-87666200-6e13-11eb-9edd-e4875c795557.png)

Con lo que decís que podes aun ver la textura en el juego, quizás tengas un wad en la carpeta cstrike que todavía contenga esas texturas. Tu solución me parece bien, pero con lo que acabo que decir, en vez de descompilar tendrías que encontrar ese wad y extraerlo.

**Comment by rolivencia** [comment]
Voy a revisar alguna de las versiones "no-steam" del CS 1.6, en las que tal vez siga estando esa versión de de_dust2 con el cartel de Gametracker incluído.

**Comment by rolivencia** [comment]
Confusión de mi parte parece. El cartel sólo lo vi cuando hice mis pruebas al texturar el mapa en CSGO. Veo, además, que al descompilar el .bsp que está en el repositorio los sólidos tampoco están.

No estoy seguro de cuál es la cuestión por la cual discrepan los mapas respecto de sólo esos dos sólidos. Sí estoy seguro de que originalmente en 3DGames lo subí dos veces y no hice circular sólo una versión. Puede ser que en su momento haya generado una versión sin el cartel, o bien la versión del mapa que se volvió "popular" sufrió una descompilación/recompilación sin los carteles. Veo menos probable esta última debido a que se notarían más diferencias entre los mapas - y luego de esta descompilación, comparando mi RMF con el .map descompilado no veo otras diferencias.

Lo que sí es preciso es que:
- Sabemos de antemano que desde el .RMF original no se podía, de cualquier manera, generar el mismo .BSP debido a la discrepancia entre los settings al ejecutar la compilación.
- Desde el .RMF original no se puede generar el mismo .BSP a partir de la discrepancia entre los sólidos.

Dicho esto, hay dos formas de solucionarlo:

- Remover los sólidos y subir esa nueva versión del RMF.
- Agregar el .wad con las texturas para, conservando el RMF original, poder hacer una apertura y lectura del RMF con la experiencia completa y sin problemas.

**Comment by WorstAquaPlayer** [comment]
> [...] y luego de esta descompilación, comparando mi RMF con el .map descompilado no veo otras diferencias.

Cuando decís "comparando mi RMF", ¿te referís al de este repositorio a uno que tenes aparte?
Si te referís al de este repositorio, es raro que digas eso de la comparacion, porque hay cosas diferentes entre ese RMF y el BSP final.
Arregle unas cosas en el RMF de este repositorio y lo puse en el Pull [**[CS 1.6] Pequeños arreglos y modificaciones al RMF** #4](https://github.com/rolivencia/de_dust2_largo/pull/4).

Volviendo a lo del issue, yo diría que se intente agregar un .wad con las texturas, aunque esto dependa de que estas sigan existiendo siquiera. Si no es posible obtener esas texturas, entonces sera removerlo del RMF por completo, lo cual no es mucho problema porque en las nuevas versiones de 1.6 ni se muestra esa textura (y al parecer ser que tampoco en videos viejos como este del 2009: https://www.youtube.com/watch?v=EU_3elcEcPw)

**Comment by rolivencia** [comment]
> Cuando decís "comparando mi RMF", ¿te referís al de este repositorio a uno que tenes aparte?
> Si te referís al de este repositorio, es raro que digas eso de la comparacion, porque hay cosas diferentes entre ese RMF y el BSP final.

Miré rápido y después noté varias otras diferencias, incluyendo la del bloque en base T que mencionás. Me resultan raras las discrepancias y el hecho de que este mismo .bsp que subí acá es el que yo tenía guardado en mi Drive. Es decir: RMF y .bsp los tenía desde fines de 2005, pero ignoro si en algún momento hice modificaciones y el RMF del cual hice el backup fue uno anterior. Se me hace imposible dilucidar esto sin tener toda la info a mano. 

De cualquier manera, viendo la ubicación de las entities y el hecho de cómo está cortada la zona de MA, más el agregado de la puerta extra cuando pasás para largo, el RMF que dió origen a ese BSP es sin duda el mío.

> Volviendo a lo del issue, yo diría que se intente agregar un .wad con las texturas, aunque esto dependa de que estas sigan existiendo siquiera. Si no es posible obtener esas texturas, entonces sera removerlo del RMF por completo, lo cual no es mucho problema porque en las nuevas versiones de 1.6 ni se muestra esa textura (y al parecer ser que tampoco en videos viejos como este del 2009: https://www.youtube.com/watch?v=EU_3elcEcPw)

Conseguí las texturas, ya tengo un .wad de de_dust2 con las que van en el cartel. Las agregamos en un .wad extra. Voy a estar buscando una herramienta para generarlos, porque no sé si Wally funcionará en Windows 10.

En tope de todo esto, voy a modificar el readme.md no sólo para incluirte en créditos sino para avisar respecto de que el .RMF no genera la misma geometría del .BSP, sino que tiene modificaciones respecto de la versión que se juega en todas partes. Creo que además es importante esto último para evitar que haya personas que intenten recompilar el mapa, subirlo a un server con el mismo nombre, y que después haya discrepancias respecto del .bsp que circula normalmente en los servers -- que es también el que está en este repositorio.

**Comment by rolivencia** [comment]
@WorstAquaPlayer: subí un PR para revisar, el #7. Cuando puedas dale una mirada. 

Los cambios:

- Se incluyó de_dust2_largo.wad
- Agregué texturas noclip para reemplazar la null en los bordes que no miran al oeste de los brushes del cartel
- Moví los brushes del cartel a la ubicación original que tienen en las versiones antiguas de de_dust2, para no solapar el cartel con las brushes de la pared lateral este de Largo.

Espero tus comentarios.
